/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java401CodeChallenges.Tree;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

}
